# Site settings
title: "Kushal Resume"
description: "Kushal Sharma"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kushal Sharma"
resume_title:                   "Android Developer | JAVA | Coding Enthusiast | Jr. CSE Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kushals0209@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 9358866021"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield â€¢ 555-7334 â€¢ lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>ğŸ‘¨â€ğŸ’»Android Developer | âœ¨ Innovator | ğŸš€ Explorer

I'm Kushal Sharma, a tech enthusiast with a knack for coding and a passion for innovation. As a Computer Science student, I've delved into the digital realm, mastering languages like Java, C++, Python, and more.

ğŸ“ My Background: Bachelor of Technology in Computer Science, Rajasthan Institute of Engineering and Technology.

ğŸŒŸ Skills: Android app development, data structures, Object oriented PRogramming, Machine learning, and more.

ğŸŒ My Soft Skills: Leadership, event management, public speaking - I bring the whole package.

ğŸŒŸ Passion: Adaptable, always learning, and forever hungry for growth.

Let's create, innovate, and make tech magic together. Feel free to connect with me on professional networks or explore my work on code-sharing platforms.

This version of the summary maintains a concise and creative snapshot of your skills and passions without mentioning your project experience or contact information. It's designed to engage the reader's interest and encourage them to seek more information through the provided networks and platforms.

</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     false
# resume_section_links:           false
# resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Kus-hal"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kushal-0602-sharma"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://drive.google.com/file/d/1rNy-Co5wSeyzR2rrKSIjQbklqfwmWRVJ/view?usp=sharing"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
